name: Scheduled Streamlit Run

on:
  schedule:
    - cron: '0 22 * * *'  # Runs every day at 8 AM UTC (adjust if needed)
  workflow_dispatch:  # Allows manual triggering if needed

jobs:
  trigger_streamlit:
    runs-on: ubuntu-latest
    steps:
      - name: Send Request to Streamlit App
        run: |
          curl -X GET "https://foxedgeai.streamlit.app/?trigger"
