name: "Daily Model Training"

on:
  schedule:
    # Runs daily at 08:00 UTC (adjust the cron expression as needed)
    - cron: "0 08 * * *"
  workflow_dispatch: {}

jobs:
  daily_train:
    runs-on: ubuntu-latest
    timeout-minutes: 180  # 3-hour timeout limit

    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Cache pip packages
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Upgrade pip and install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install monitoring tools
        run: sudo apt-get install -y htop

      - name: System information
        run: |
          echo "CPU Info:"
          lscpu
          echo "Memory Info:"
          free -h
          echo "Disk Space:"
          df -h

      - name: Run training script
        run: |
          python train.py
        shell: /usr/bin/bash -e {0}
        env:
          pythonLocation: /opt/hostedtoolcache/Python/3.9.21/x64
          LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.9.21/x64/lib

      - name: List model files after training
        run: ls -l models

      - name: Commit and push updated models
        env:
          PUSH_TOKEN: ${{ secrets.PUSH_TOKEN }}
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add models/
          if ! git diff --cached --quiet; then
            git commit -m "Update models from daily training $(date)"
            git push https://x-access-token:${{ secrets.PUSH_TOKEN }}@github.com/weballin02/FoxEdge.git HEAD:main
          else
            echo "No changes to commit."
          fi
