name: "Daily Model Training"

on:
  schedule:
    # Runs every day at 11:00 UTC (which is 3:00 AM PT in winter, 4:00 AM in summer)
    - cron: "0 11 * * *"
  workflow_dispatch: {}  # Enables manual triggering of the workflow

jobs:
  daily_train:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run training script
        run: python train.py
